### ISSUE TITLE
docs: #21~#23 models issue

### ISSUE THREAD

**Issue by heejung-gjt** [Neo-News/Neo-News#24]
**models.py 변경해야 하는 부분**
- [x] user 프로필 이미지 네이밍 image로 변경하기
- [x] 모델 필드는 전부 한줄로 변경하기 
- [x] UserManager 내부에 있는 2개의 메서드들 키워드 알규먼트 변경하기
- [x] is_active: False로 변경하기 (이메일 인증 문제)
- [x] User에 TimeStampable, Deleteable 추가하기
- [x] 좋아요 카운트 count()메서드로 변경하기(fat-model)
- [x] n:n 변수명 복수로 변경하기
- [x] 스페이스 4개 컨벤션 지키기

**발생한 이슈**
- ValueError: Dependency on app with no migrations: user 에러 발생
앱 만든 후 makemigrations/migrate해주지 않아서 발생한 에러, pull 받고 mysql연동시킨 후 migrate하면 사라질거라고 예상합니다.:-)

- forms.py 따로 커스터마이징 필요합니다.

- user 상속 받은 부분 , **kwargs 쓰는거 생각해봐야 합니다.

**생각할 부분**
- 장고 테스트 코드 (2-3개에 대한 기능 테스트 하는 로직 짜보기)
- 공유하기 버튼 - 카카오톡은 불가능 , 페이스북등으로 대체

**Comment by Odreystella** [comment]
mysqlclient설치 -> settings.py 설정 후 migrate해서 MySQL - django 연동 완료!
유저 모델 확장(feat.is_staff) 완료!
